/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labo03;
/**
 *
 * @author Usuario
 */
public class CalculadoraGUI extends javax.swing.JFrame {
    private double numero1 = 0;
    private String operador = "";
    private boolean limpiarPantalla = false;
    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }
    private void agregarNumero(String numero) {
        if (limpiarPantalla || jTextField1.getText().equals("0")) {
            jTextField1.setText(numero);
            limpiarPantalla = false;
        } else {
            jTextField1.setText(jTextField1.getText() + numero);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_siete = new javax.swing.JButton();
        jButton_ocho = new javax.swing.JButton();
        jButton_cinco = new javax.swing.JButton();
        jButton_nueve = new javax.swing.JButton();
        jButton_sies = new javax.swing.JButton();
        jButton_cuatro = new javax.swing.JButton();
        jButton_uno = new javax.swing.JButton();
        jButton_dos = new javax.swing.JButton();
        jButton_cero = new javax.swing.JButton();
        jButton_tres = new javax.swing.JButton();
        jButton_suma = new javax.swing.JButton();
        jButton_multiplicacion = new javax.swing.JButton();
        jButton_resta = new javax.swing.JButton();
        jButton_division = new javax.swing.JButton();
        jButton_resultado = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_siete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_siete.setText("7");
        jButton_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sieteActionPerformed(evt);
            }
        });

        jButton_ocho.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ocho.setText("8");
        jButton_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ochoActionPerformed(evt);
            }
        });

        jButton_cinco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_cinco.setText("5");
        jButton_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cincoActionPerformed(evt);
            }
        });

        jButton_nueve.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_nueve.setText("9");
        jButton_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nueveActionPerformed(evt);
            }
        });

        jButton_sies.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_sies.setText("6");
        jButton_sies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siesActionPerformed(evt);
            }
        });

        jButton_cuatro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_cuatro.setText("4");
        jButton_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cuatroActionPerformed(evt);
            }
        });

        jButton_uno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_uno.setText("1");
        jButton_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_unoActionPerformed(evt);
            }
        });

        jButton_dos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_dos.setText("2");
        jButton_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dosActionPerformed(evt);
            }
        });

        jButton_cero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_cero.setText("0");
        jButton_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ceroActionPerformed(evt);
            }
        });

        jButton_tres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_tres.setText("3");
        jButton_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tresActionPerformed(evt);
            }
        });

        jButton_suma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_suma.setText("+");
        jButton_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sumaActionPerformed(evt);
            }
        });

        jButton_multiplicacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_multiplicacion.setText("*");
        jButton_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiplicacionActionPerformed(evt);
            }
        });

        jButton_resta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_resta.setText("-");
        jButton_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restaActionPerformed(evt);
            }
        });

        jButton_division.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_division.setText("/");
        jButton_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_divisionActionPerformed(evt);
            }
        });

        jButton_resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_resultado.setText("=");
        jButton_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resultadoActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jButton_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jButton_sies, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jButton_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_division, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_sies, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_division, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sieteActionPerformed
        // TODO add your handling code here:
        agregarNumero("7");
    }//GEN-LAST:event_jButton_sieteActionPerformed

    private void jButton_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ochoActionPerformed
        // TODO add your handling code here:
        agregarNumero("8");
    }//GEN-LAST:event_jButton_ochoActionPerformed

    private void jButton_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cincoActionPerformed
        // TODO add your handling code here:
        agregarNumero("5");
    }//GEN-LAST:event_jButton_cincoActionPerformed

    private void jButton_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nueveActionPerformed
        // TODO add your handling code here:
        agregarNumero("9");
    }//GEN-LAST:event_jButton_nueveActionPerformed

    private void jButton_siesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siesActionPerformed
        // TODO add your handling code here:
        agregarNumero("6");
    }//GEN-LAST:event_jButton_siesActionPerformed

    private void jButton_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cuatroActionPerformed
        // TODO add your handling code here:
        agregarNumero("4");
    }//GEN-LAST:event_jButton_cuatroActionPerformed

    private void jButton_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_unoActionPerformed
        // TODO add your handling code here:
        agregarNumero("1");
    }//GEN-LAST:event_jButton_unoActionPerformed

    private void jButton_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dosActionPerformed
        // TODO add your handling code here:
        agregarNumero("2");
    }//GEN-LAST:event_jButton_dosActionPerformed

    private void jButton_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ceroActionPerformed
        // TODO add your handling code here:
        agregarNumero("0");
    }//GEN-LAST:event_jButton_ceroActionPerformed

    private void jButton_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tresActionPerformed
        // TODO add your handling code here:
        agregarNumero("3");
    }//GEN-LAST:event_jButton_tresActionPerformed

    private void jButton_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sumaActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(jTextField1.getText());
        operador = "+";
        limpiarPantalla = true;
    }//GEN-LAST:event_jButton_sumaActionPerformed

    private void jButton_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiplicacionActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(jTextField1.getText());
        operador = "*";
        limpiarPantalla = true;
    }//GEN-LAST:event_jButton_multiplicacionActionPerformed

    private void jButton_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restaActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(jTextField1.getText());
        operador = "-";
        limpiarPantalla = true;
    }//GEN-LAST:event_jButton_restaActionPerformed

    private void jButton_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_divisionActionPerformed
        // TODO add your handling code here:
        numero1 = Double.parseDouble(jTextField1.getText());
        operador = "/";
        limpiarPantalla = true;
    }//GEN-LAST:event_jButton_divisionActionPerformed

    private void jButton_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resultadoActionPerformed
        // TODO add your handling code here:
         double numero2 = Double.parseDouble(jTextField1.getText());
        double resultado = 0;

        switch (operador) {
            case "+":
                resultado = numero1 + numero2;
                break;
            case "-":
                resultado = numero1 - numero2;
                break;
            case "*":
                resultado = numero1 * numero2;
                break;
            case "/":
                if (numero2 != 0) {
                    resultado = numero1 / numero2;
                } else {
                    jTextField1.setText("Error");
                    return;
                }
                break;
        }

        jTextField1.setText(String.valueOf(resultado));
        limpiarPantalla = true;
    }//GEN-LAST:event_jButton_resultadoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cero;
    private javax.swing.JButton jButton_cinco;
    private javax.swing.JButton jButton_cuatro;
    private javax.swing.JButton jButton_division;
    private javax.swing.JButton jButton_dos;
    private javax.swing.JButton jButton_multiplicacion;
    private javax.swing.JButton jButton_nueve;
    private javax.swing.JButton jButton_ocho;
    private javax.swing.JButton jButton_resta;
    private javax.swing.JButton jButton_resultado;
    private javax.swing.JButton jButton_sies;
    private javax.swing.JButton jButton_siete;
    private javax.swing.JButton jButton_suma;
    private javax.swing.JButton jButton_tres;
    private javax.swing.JButton jButton_uno;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
